# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20170724_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
