# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_client_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='optin',
            field=models.BooleanField(default=True),
        ),
    ]
